version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.70
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: cargo test
      - run:
          name: Build
          command: carbo build
